id: P000423
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-16 15:39:12.858802
source_metadata:
  id: bdr:W8LS20320
  title: འཕྲོད་བསྟེན་གྱི་རྒྱུན་ཤེས་ཀློག་དེབ།
  author: ''
  volumes:
    d2d25d8bf8e64cf7b6ea4f57a4cb6086:
      image_group_id: I8LS20322
      title: Volume 1 of phrod bsten gyi rgyun shes klog deb/
      volume_number: 1
      total_pages: 241
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
